CREATE CAST (VARCHAR AS DATE) WITH INOUT AS IMPLICIT;

CREATE TABLE students (
	id BIGSERIAL PRIMARY KEY,
	surname VARCHAR(30) NOT NULL,
	name VARCHAR(30) NOT NULL,
	patronymic VARCHAR(30) NOT NULL,
	date_of_birth DATE NOT NULL,
	group_id VARCHAR(10) NOT NULL
);